<div id="custom-accordion">
    <div id="element"  data-mage-init='
                        {
                            "accordion":
                            {
                                "openedState": "active",
                                "collapsible": true,
                                "active": false,
                                "multipleCollapsible": false,
                                "header":"[data-role=trigger]"
                            }
                        }'>
        <div data-role="collapsible">
            <div data-role="trigger">
                <span>Title 1</span>
            </div>
        </div>
        <div data-role="content">Content 1</div>

        <div data-role="collapsible">
            <div data-role="trigger">
                <span>Title 2</span>
            </div>
        </div>
        <div data-role="content">Content 2</div>

        <div data-role="collapsible">
            <div data-role="trigger">
                <span>Title 3</span>
            </div>
        </div>
        <div data-role="content">Content 3</div>
    </div>

    <button tabindex="0"
            title="This is tooltip text"
            data-mage-init='{
                    "tooltip": {
                        "content": "This is tooltip text"
                    }
                 }'>
        This is button with tooltip
    </button>

</div>

